### ISSUE TITLE
Examples do not work after r2ai install

### ISSUE THREAD

**Issue by cryptax** [radareorg/r2ai#103]
Installed `r2pm -r r2ai r2ai-plugin`.
The example `conversation.r2.js` does not work straight out of the box.

```
$ node conversation.r2.js 
/home/axelle/git/r2ai/examples/conversation.r2.js:4
		r2.call(`r2ai -n ${num}`)
		^

ReferenceError: r2 is not defined
    at new R2AI (/home/axelle/git/r2ai/examples/conversation.r2.js:4:3)
    at /home/axelle/git/r2ai/examples/conversation.r2.js:37:12
    at Object.<anonymous> (/home/axelle/git/r2ai/examples/conversation.r2.js:66:3)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
    at node:internal/main/run_main_module:28:49
```

**Comment by trufae** [comment]
.r2.js scripts are not nodejs programs, but r2 programs, you must execute them with `r2 -i foo.r2.js`. or from inside r2 with the `. ` command like in any other script
